#!/bin/bash
rm -rf bld
mkdir bld

cd server/neo4j/packaging/standalone/
	mvn clean package
	cd ../../../..

cp server/neo4j/packaging/standalone/target/neo4j-community-3.1.1-SNAPSHOT-unix.tar.gz bld/
cp -r server/dump bld/dump
cp server/api.js bld/api.js

cd bld
	npm install request

	tar -xvf neo4j-community-3.1.1-SNAPSHOT-unix.tar.gz
#	rm -rf neo4j-community-3.1.1-SNAPSHOT/data/databases/graph.db
#	mv dump neo4j-community-3.1.1-SNAPSHOT/data/databases/graph.db
	neo4j-community-3.1.1-SNAPSHOT/bin/neo4j start
		read -p "Please open http://localhost:7474 and change the default password. Then press return."
	neo4j-community-3.1.1-SNAPSHOT/bin/neo4j stop
cd ..
